FROM python:3.12-alpine

WORKDIR /app

# Устанавливаем зависимости
RUN apk add --no-cache gcc musl-dev linux-headers && \
    pip install --no-cache-dir flask stem docker requests watchdog PySocks geoip2

# Копируем файлы
COPY manager.py .
COPY templates/ ./templates/
COPY static/ ./static/
COPY config.json /app/config.json
COPY GeoLite2-City.mmdb /app/GeoLite2-City.mmdb

CMD ["python", "manager.py"]
